liqotech/dashboard

kubernetes/config/dashboard-configmap.yaml
kubernetes/config/dashboard-deploy.yaml
kubernetes/config/dashboard-ingress.yaml
kubernetes/config/dashboard-sa-crb.yaml
kubernetes/config/dashboard-svc.yaml

This PR changes namespace and label specifications to LiqoDash resources in order to achieve an easier interaction with the [**Liqo Agent**](https://github.com/LiqoTech/liqo/tree/master/cmd/tray-agent) component.
- updated LiqoDash docker image
- transition from *default* to **liqo** namespace
- added **app:liqo-dashboard** label

Integration of LiqoDash with Liqo Agent

---

__mocks__/advertisement_noStatus.json
__mocks__/advertisement_notAccepted.json
__mocks__/advertisement_refused.json
__mocks__/crd_fetch.json
__mocks__/crd_fetch_long.json
__mocks__/foreigncluster_noIncoming.json
__mocks__/foreigncluster_noOutgoing.json
src/home/ConnectedPeer.js
src/home/HomeUtils.js
src/home/ListConnected.js
test/AppHeader.test.js
test/CR.test.js
test/ConnectedPeer.test.js
test/DesignEditorCRD.test.js
test/GraphNet.test.js
test/Home.test.js

This PR adds the list of connected peers to the home view.
Each item of the list represents a join between the home cluster and a foreign cluster. It also shows the direction of the connection and the general consumption of the cluster. There's also the possibility to disconnect from a peer with a simple click.

LIQO home view - list of connected peers

---

__mocks__/crd_fetch.json
__mocks__/foreigncluster_noJoin.json
__mocks__/searchdomain.json
jest.setup.js
package.json
src/home/AvailablePeer.js
src/home/Home.js
src/home/ListAvailable.js
src/services/__mocks__/ApiManager.js
test/AvailableList.test.js
test/AvailablePeer.test.js
test/CRDList.test.js
test/ConnectedList.test.js
test/ConnectedPeer.test.js
test/RTLUtils.js
test/SideBar.test.js

This PR adds the list of available peers to the home view.
Each item of the list represents a peer (foreign cluster) that has been discovered and can be joined with the home cluster. It also shows the type of the connection (if the foreign cluster is in the same LAN as the home cluster or not). There's the possibility to connect to connect with a peer with a simple click. It also describes the status of the connecting process and, in case of connection error, in what phase of the connecting process the error has shown.

LIQO home view - list of available peers

---

__mocks__/advertisement.json
__mocks__/pods.json
src/constants/index.js
src/home/ConnectedPeer.js
src/home/ConnectionDetails.js
src/home/HomeUtils.js
src/home/ListAvailable.js
src/home/ListConnected.js
src/services/ApiManager.js
src/services/__mocks__/ApiManager.js
test/AvailableList.test.js
test/AvailablePeer.test.js
test/CR.test.js
test/ConnectedList.test.js
test/ConnectedPeer.test.js
test/ConnectionDetails.test.js
test/PeerProperties.test.js
test/RTLUtils.js

This PR introduces a view of the detail for a given peer connection.
The details showed are the following:
- General tab: rather empty for now, meant to show some general information of the connection (for now, only shows the direction of the connection)
- Home tab: shows the **foreign cluster**'s consumption of resources in the **home cluster**, as well as a list of the pods that the **foreign cluster** has offloaded to the **home cluster**. It also show the total consumption of these pods relative to the consumption limit established. 
- Foreign tab: same as the Home tab, but the direction of the consumption relationship is inverted.
If the connection is not mutual, one of the two tabs are not showed (e.g. if only I can use your resources, but you are not allowed to use mine, there will …

LIQO home view -peer connection details

---

__mocks__/advertisement.json
__mocks__/nodes.json
__mocks__/nodes_metrics.json
__mocks__/pods.json
__mocks__/pods_metrics.json
src/home/ConnectedPeer.js
src/home/ConnectionDetails.js
src/home/Home.js
src/home/ListConnected.js
src/services/ApiManager.js
src/services/__mocks__/ApiManager.js
test/AppHeader.test.js
test/AvailableList.test.js
test/AvailablePeer.test.js
test/CRD.test.js
test/ConfigView.test.js
test/ConnectedList.test.js
test/ConnectedPeer.test.js
test/ConnectionDetails.test.js
test/DesignEditorCRD.test.js
test/FormViewer.test.js
test/Home.test.js
test/PeerProperties.test.js
test/RTLUtils.js
test/SideBar.test.js

This PR adds the real-time monitoring of a single connection (peering), visible directly in the general view (a circle around the home cluster and/or the foreign home, depending if there is resource consumption, that shows the % of how much memory is being consumed) or more specific in the details view.
In details:
- The statistic is based on how many resources (CPU/RAM) are consumed by the sum of the pods offloaded in the other cluster, in relationship to how much resource sharing is established (e.g. I am connected with the foreign cluster X. In the advertisement of foreign cluster X it is established that it will share with me 5GB of RAM, and the sum of the consumed RAM of my pods offloaded to the foreign cluster is 1GB, that means I am using 20% of the available RAM in the foreign …

LIQO home view - connection (peering) status and metrics

---

kubernetes/config/dashboard-sa-crb.yaml

This PR updates the cluster role binding configuration deleting the definition of a namespace. Without that namespace the secret created can be used to access the entire cluster (previously that secret would have granted permission to access only the defined namespace)

Update cluster role binding

---

__mocks__/pods.json
__mocks__/pods_metrics.json
src/home/ConnectedPeer.js
src/home/ConnectionDetails.js
src/home/HomeUtils.js
src/home/ListConnected.js
src/home/Status.js
src/services/ApiManager.js
src/services/__mocks__/ApiManager.js
test/ConnectedPeer.test.js
test/RTLUtils.js
test/Status.test.js

With this PR when fetching the metrics server returns a 404 (or when the nodes metrics return an empty list for the physical and/or virtual nodes), the worst case scenario metrics are used. That means that the consumption of a single pod will be the requested resources of that pod, and the total consumed % of RAM/CPU is the sum of the pods' requested resources.
**Note that assuming the worst case scenario implies that the total consumed resources could be more than 100%, even though the actual total consumed resources is lower.**

LIQO home view - pods metrics when there is no metrics server available

---

generate_config_js.sh
kubernetes/config/dashboard-configmap.yaml
kubernetes/config/dashboard-deploy.yaml
kubernetes/config/dashboard-svc.yaml
nginx.conf
src/app/App.js
src/services/ApiManager.js
src/services/__mocks__/Authenticator.js
test/App.test.js
webpack.config.js
webpack_docker.config.js

This PR adds a proxy in the nginx configuration. The connection with the proxy is over TLS (with the certificate and key created by a sidecar container) and using HTTP/2. 
Using a proxy to manage the call to the Kubernetes api server, there is no need to specify it in the dashboard, that will just call a path preceded by _/apiserver_ and then the proxy will forward it to the actual Kubernetes api server.

Added nginx proxy

---

src/home/ConnectedPeer.js
src/home/ConnectionDetails.js
src/home/Status.js

This PR adds a little "!" when there is no metrics server available to retrieve the actual status of the clusters, notifying the user that there is no metrics server available (either for the home cluster, or the foreign ones).
The icon will show up in the details of the connection and in the status view.

Home view shows when there is no metrics server

---

src/home/ConnectedPeer.js
src/home/Status.js
test/Status.test.js

This PR handles situations where the api server responds with a 404 when asked for nodes metrics. The way it handles it is the same as when the response is an empty list, that is considering every pod in the cluster (not the ones offloaded to other foreign clusters) consuming so much cpu and memory as specified in the request parameter of that pod.

Nodes metrics when metrics server respond with 404

---

__mocks__/configs.json
__mocks__/configs_updated.json
src/home/ConnectedPeer.js

This little PR fixes a bug where the home view would show a NaN or 0% of resources consumed for the connected peers (only for the incoming pods). That was because of a wrong call to a clusterConfig's parameter.

Fix metrics showing NaN on connected peer

---

.github/workflows/node.js.yml

This PR fixes the pipeline if clause when building a release tag and remove useless npm build before the actual docker build.

Fix branch if clause whem building tags

---

__mocks__/pods.json
src/home/ConnectedPeer.js
src/home/ConnectionDetails.js
test/ConnectedPeer.test.js

This PR handles the situations where a pod (or one of its containers) has no requested resources specified. That means that even when there is a metrics server that can tell how many resources that pod is consuming, there is no way to transform that number in percentage (because there are no upper limits). So, while always showing how much resources a pod is **consuming**, the **reserved** will be 0. Also, to notify the user that a pod has no requested resources specified, a little "!" is placed next to the pod's name, and hovering with the mouse over it will let the user know what's the problem.

Metrics when a pod has no requested resources

---

src/app/App.js
src/home/Home.js
src/services/Authenticator.js
src/templates/donut/Donut.js
src/templates/line/LineChart.js
test/App.test.js
test/Login.test.js

With this PR, the dashboard waits for the OIDC login to complete before showing any view. That prevents some discrepancy in the CRDs fetched and the data visualization in the home view.
Other minor features:
- The token used for the authentication is now stored in a cookie even with the OIDC login (instead of the session storage).
- Managed situations where calculations of the percentages of the clusters return NaN or Infinity.
- Managed situations where the Liqo CRD are added after the Home View is displayed (so there is no need to refresh the page!).

Dashboard wait for OIDC login to complete before showing views

---

__mocks__/views_another.json
src/CRD/CRD.js
src/common/SideBar.js
src/services/__mocks__/ApiManager.js
src/services/stringUtils.js
src/views/AddCustomView.js
test/CRD.test.js
test/CRDList.test.js
test/RTLUtils.js
test/SideBar.test.js

This PR introduces two new and more direct (and easy) way to create a custom view:
- From the sidebar, clicking the 'New Custom View' menu item will open a modal where the name of the custom view can be choose and the CRDs to put in it (with an autocomplete function that let you choose from the CRD that are present in your cluster)
- From a CRD, clicking the 'New Custom View' menu item under the views dropdown menu. It will open a modal identical to the one described above, but with the CRD you are on already inserted.
**NOTE:** the views are created in the _default_ namespace

Easy custom view creator

---

src/home/Status.js

This little PR fixes a bug where the metrics from the metrics server for the home cluster were not considered, displaying the not precise ones.

Fix status home nodes not getting metrics

---

__mocks__/pods.json
src/home/Status.js
test/ConnectedList.test.js

This PR manages a particular bug where if there is no metrics server and a pod has no node-name specified, it would compromise the calculation of the other pods metrics, meaning that even with just one pod with an unspecified node-name the view would display 0% consumed.

Manage pod with no node-name in status view

---

src/CRD/CRDList.css
src/CRD/CRDList.js
src/home/ConnectionDetails.js
src/services/TableUtils.js
test/CRDList.test.js

In this PR:
- code refactoring of CRD list view (from react class to function that use hooks)
- the position of the _search_ filter in the CRD table columns header is now beside the column it refers to;
- introduced a new _favourite_ filter, allowing the user to filter by favourite CRDs;
- introduced multiple filtering selection functions, allowing the user to use different filters together;
For example, here we see the CRDs filtered by group and by favourite.

CRD list view - updated filters and code refactoring

---

__mocks__/configs.json
__mocks__/configs_updated.json
__mocks__/crd_fetch.json
__mocks__/foreigncluster.json
__mocks__/foreigncluster_new.json
__mocks__/foreigncluster_noIncoming.json
__mocks__/foreigncluster_noJoin.json
__mocks__/foreigncluster_noOutgoing.json
src/home/AvailablePeer.js
src/home/ConnectedPeer.js
src/home/ConnectionDetails.js
src/home/LiqoHeader.js
test/AvailableList.test.js
test/AvailablePeer.test.js
test/ConnectedList.test.js
test/ConnectedPeer.test.js
test/ConnectionDetails.test.js
test/PeerProperties.test.js
test/Status.test.js

This PR updates the home view so that now the clusters' names are displayed instead of their cluster-ids. Besides, hovering over the foreign cluster's name will prompt a tooltip showing the cluster-id. Also, the user's cluster name is displayed in the header of the home view.

Show name of foreign clusters instead of ID

---

src/home/LiqoHeader.js
src/home/ListAvailable.js
src/home/ListConnected.js
test/Home.test.js
test/LiqoHeader.test.js
test/Status.test.js

This PR makes the cluster name editable right in the home view, without the need to go to modify it in the cluster config. Just clicking on it in the header of the home view will let you modify it. To save the changes, you can just press enter or click away.

Update cluster name to be easily editable

---

__mocks__/dashboardconf.json
jest.setup.js
src/app/App.js
src/common/SideBar.css
src/common/SideBar.js
src/resources/common/CustomIcon.js
src/resources/common/DashboardConfigUtils.js
src/resources/common/buttons/FavouriteButton.js
src/resources/common/buttons/IconButton.js
src/resources/resource/ResourceGeneral.js
src/resources/resource/ResourceHeader.js
src/resources/resourceList/ListHeader.js
src/resources/resourceList/ResourceList.js
src/services/api/ApiInterface.js
src/services/api/__mocks__/ApiManager.js
test/APIGroupList.test.js
test/CRD.test.js
test/DashboardConfig.test.js
test/FavouriteAndIcon.test.js
test/ResourceList.test.js

With this PR the user can mark a resource (list or single resource) as favourite and it will be displayed accordingly in the related views. Resource's kinds marked as favourite (deployments, pods, CRDs...) will also pop up in the sidebar for easy access. Single resources marked as favourite can be filtered in the resource list view.
Also added support for icon customization on resource list views and sidebar favourites. When no icon is selected will be used the default icon.

Favourites and custom Icons

---

src/common/ResourceAutocomplete.js
src/services/Utils.js

This PR fix a minor bug where if two CRDs are updated at the same time, triggering the update of the resources shown in the autocomplete search in the header, that would lead to some of these resources doubled in the autocomplete search dropdown.

Header search autocomplete bug fix

---

src/editors/Editor.js
src/resources/resource/ResourceGeneral.js
test/NewResource.test.js
test/UpdateCR.test.js

This PR adds the possibility to choose between YAML or JSON in the editor used to create/update resources, while so far only the JSON option was given.

Switchable language in editor (YAML or JSON)

---

package.json
src/app/CR.css
src/resources/APIGroup/APIGroupList.js
src/resources/APIResourceList/APIResourceList.js
src/resources/resourceList/ResourceList.js
src/services/TableUtils.js

This PR adds the possibility to manage the column width of tables in the dashboard.
The modifications are NOT saved after the user leave the page, so with a refresh of the page the column widths will return to the default ones, but it is nonetheless a useful feature for various cases.

Add resizable column width on table

---

src/common/NamespaceSelect.js
src/editors/CRD/NewFromFile.js
src/editors/CRD/NewResource.js
src/services/Utils.js

With this PR is now possible to import a series of resources of the same kind from a CSV file, using the same method of creating a new resource (from the editor or the form wizard if available) and going to the `Import File` tab.
- This new method allows to create more resources of the same kind at once.
- The CSV file needs to contain the values of the `spec` of the resource.
- The names of the resources created are generated using the kind of the resource followed by a random number to guarantee the uniqueness of the resource.
- If the resource is namespaced, a namespace can be selected **for all the resources imported** (default namespace is `default`).
- If the CSV file contains more than one resource, a subset of the resources can be selected to be imported. The resources not …

Add new resource from CSV file

---

src/editors/OAPIV3FormGenerator/CustomFieldTemplate.js
src/editors/OAPIV3FormGenerator/CustomFieldTemplateViewer.js
src/editors/OAPIV3FormGenerator/CustomWidget.js
src/editors/OAPIV3FormGenerator/FormGenerator.js
src/editors/OAPIV3FormGenerator/ReferenceHandler.js
src/resources/common/ResourceUtils.js
src/resources/resource/ReferenceTab.js
src/resources/resource/ResourceGeneral.js
src/resources/resource/ResourceHeader.js
src/resources/resourceList/ResourceList.js
src/services/Colors.js
src/services/Utils.js
src/services/stringUtils.js
src/views/liqo/HomeUtils.js
src/widgets/donut/Donut.js
src/widgets/form/FormViewer.js
src/widgets/graph/GraphNet.css
src/widgets/graph/GraphNet.js
test/CustomTab.test.js

This PR introduces a new way of handling links between Kubernetes objects. This method requires a resource to reference another in a certain way that has to be specified in the schema of the resource. So, in the schema of a CRD that references another resource, we have to create a field named as follows: `{REFERENCED_CRD_SINGULAR_NAME}.{REFERENCED_CRD_GROUP}/{REFERENCED_CRD_KIND}Ref`. That is an object with two parameters: 
- `name`: the name of the referenced resource
- `namespace`: the namespace in which the referenced resource resides (optional, if the referenced CRD is namespaced or not)
For example, if we want our CRD to reference another CRD, the yaml of the first CRD schema should be something like this:
```
...
workspace.examplegroup.com/WorkspaceRef:
type: object
required:
- name …
```

Direct object references management and Linked Resource tab

---

src/editors/OAPIV3FormGenerator/FormGenerator.js
src/services/Utils.js
test/NewResource.test.js

This PR fixes a bug that would reset the form wizard of a creating resource when another resource showed in the view is updated or added (or a corresponding watch triggered/closed/restarted).

Fix form reset when creating resource

---

src/resources/common/KubernetesSchemaAutocomplete.js

In this PR: the options of the dropdown menu that shows the possible parameters of a resource that can be displayed (e.g. when searching for a parameter in the resource view or selecting a parameter to add in a new column in the table showing a list of resources) are now grouped by path to help the user have a better understanding of their resources and reduce verbosity (and overall confusion).

Schema autocomplete searchbar options grouped by path

---

docker-entrypoint.sh
kubernetes/dashboard_chart/templates/liqodash_deployment.yaml

With this PR it is possible to change the title and favicon of the application (the title and the icon that is seen in the browser tab), changing it in the dashboard configmap (named: `liqo-dashboard-configmap` in the namespace of installation, parameters `app_favicon` and `app_title`).
When the configmap is edited, to see the changes applied in the dashboard a restart of the deployment is needed, for example if the dashboard is installed in the namespace `liqo`, to restart the deployment we need the command:
```
kubectl rollout restart deployment liqo-dashboard -n liqo
```

Add customizable app title and favicon

---

src/services/TableUtils.js

This quick fix will prevent the browser's default tooltip from spawning when hovering over table cells.

Fix table tooltip

---

src/common/AppHeader.js
src/customView/CustomViewUtils.js
src/themes/ThemeModifier.js

This PR makes the header menu responsive based on the large and medium breakpoints. That means when the window size is less than 1000px the menu in the header bar will be automatically collapsed into a dropdown menu, to facilitate the navigation and avoid overlapping components.
Example of a collapsed header menu with some custom buttons:

Add responsive header menu

---

src/customView/CustomView.css
src/resources/resource/CustomTab.js
src/resources/resource/CustomTabContent.js
src/widgets/draggableLayout/DraggableLayout.js
src/widgets/table/TableViewer.js
test/CustomTab.test.js

Thanks to this PR is now possible to use the `layout widget` to create a responsive layout based on the browser window breakpoints. 
For example, if we want two cards to be arranged one near the other when the window is large, but one above the other when the window is reduced, we can do it by giving the two cards different layouts for different breakpoints.
So, `card #1` layout:
```
data-grid={{
lg: { w: 10, h: 38, x: 0, y: 0 },
md: { w: 24, h: 38, x: 0, y: 0 },
sm: { w: 24, h: 38, x: 0, y: 0 }
}}
```
And `card #2` layout:
```
data-grid={{
lg: { w: 14, h: 38, x: 10, y: 0 },
md: { w: 24, h: 38, x: 10, y: 0 },
sm: { w: 24, h: 38, x: 10, y: 0 }
}}
```
Layout when breakpoint is `lg` (window size larger than 1000px):
Layout on every other breakpoint (window size less than 1000px):
Without the …

Responsive layout widget
