.github/workflows/rebase.yml
This commit adds a pipeline to automate rebasing across different branches w.r.t. master branch.
=> Adding Rebase Pipeline

__mocks__/advertisement.json, __mocks__/configs.json, __mocks__/crd_fetch.json, src/editors/OAPIV3FormGenerator/CustomFieldTemplate.js, src/editors/OAPIV3FormGenerator/CustomSchemaField.js, src/editors/OAPIV3FormGenerator/CustomWidget.js, test/ConfigView.test.js, test/FormViewer.test.js
This PR update the tests regarding the CR dynamic form generator viewer and editor.
=> Test Updated

__mocks__/views_alt_template.json, __mocks__/views_withLayout.json, jest.setup.js, src/CRD/CR.js, src/CRD/CRD.js, src/app/App.js, src/home/Home.js, src/services/__mocks__/ApiManager.js, src/services/__mocks__/Authenticator.js, src/views/CustomView.js, src/views/CustomViewUtils.js, test/App.test.js, test/CRD.test.js, test/ConfigView.test.js, test/CustomView.test.js, test/RTLUtils.js
This PR updates the test suite regarding the CRDs views, custom views and added a simple OIDC test.
Also fixed a minor bug (drawers' destroy property on CRD view)
=> Updated tests for CRDs view and custom views and added OIDC test

src/home/AvailablePeer.js, src/home/ConnectedPeer.js, src/home/HomeUtils.js, src/home/ListAvailable.js, src/home/PeerProperties.js, test/PeerProperties.test.js
This PR introduces a view of the properties of a foreign cluster and all it's associated resources.
The resources that can be viewed (and also modified) this way are the following:
- Foreign cluster
- Advertisement (if there is one)
- Peering Request (if there is one)
=> LIQO home view - peer properties

.github/workflows/node.js.yml
This PR fixes the pipeline docker bug. Also it sends a slack notification when a PR is merged
=> Update pipeline and add slack notification

.github/workflows/node.js.yml
This PR updates the pipeline's docker tags when pushing on master, adding an additional tag
=> Update pipeline's docker tags when pushing on master 

__mocks__/advertisement.json, __mocks__/advertisement_refused.json, src/home/HomeUtils.js
This simple PR fixes the check of the status advertisement done in the Home view.
=> Update advertisement status check

kubernetes/config/dashboard-deploy.yaml
This PR fixes an indentation problem in the deploy yaml
=> Fix dashboard deploy indentation

.github/workflows/node.js.yml
This PR updates the pipeline to get the version and build an image tagged with this version.
=> Update pipeline build with version tag

src/CRD/CR.js, src/CRD/CRD.js
This PR fixes a little bug that prevents the CR's form to update when the CR is changed somewhere else not in the dashboard.
=> Fix automatic refresh of CRs

src/CRD/CRDList.js
This PR fixes a minor graphical bug where the "favourite" parameter of a CRD in the CRD list view did not update when the CRS was changed somewhere else not in the dashboard.
=> Fix CRD list view favourite update

src/editors/OAPIV3FormGenerator/FormGenerator.js, src/home/Home.css, src/home/Home.js, src/home/ListAvailable.js, src/home/ListConnected.js, src/home/Status.js, test/FormViewer.test.js
This PR makes makes the headers of the various sections that compose the home view fixed, so that when scrolled down the title of the section remains visible.
It also fixes a minor graphical bug where the handle used to resize each section would follow the inner component, not remaining fixed at the bottom right corner.
=> Fixed resizable handles and update home view sections headers

__mocks__/advertisement.json, src/home/ConnectedPeer.js
This simple PR updates the retrieval of the virtual node's name for a connected peer.
=> Update get vnode name from advertisement

__mocks__/crd_fetch.json, __mocks__/crd_fetch_long.json, __mocks__/views.json, __mocks__/views_alt_template.json, __mocks__/views_empty.json, __mocks__/views_modified.json, __mocks__/views_withLayout.json, kubernetes/config/dashboard-ingress.yaml, kubernetes/crd/dashboard.liqo.io_views.yaml, src/CRD/CRD.js, src/common/SideBar.js, src/services/ApiManager.js, src/services/__mocks__/ApiManager.js, src/views/CustomView.js
This PR updates the custom views crd parameters and how they are fetched by the dashboard.
=> Update custom view crd api

__mocks__/configmap_clusterID.json, src/constants/index.js, src/home/AvailablePeer.js, src/home/ConnectedPeer.js, src/home/ConnectionDetails.js, src/home/Home.js, src/home/HomeUtils.js, src/home/LiqoHeader.js, src/home/ListAvailable.js, src/home/ListConnected.js, src/home/PeerProperties.js, src/home/Status.js, src/services/ApiManager.js, src/services/__mocks__/ApiManager.js, test/App.test.js, test/AvailableList.test.js, test/AvailablePeer.test.js, test/ConfigView.test.js, test/ConnectedList.test.js, test/ConnectedPeer.test.js, test/ConnectionDetails.test.js, test/Home.test.js, test/RTLUtils.js, test/Status.test.js
This PR adds the Cluster ID to the header of the home view as a copyable text.
As a side note, I also did a bit of code refactoring, replacing React Classes with functions that use Hooks.
=> Cluster ID to home view

src/services/ApiManager.js
This PR fixes a minor bug that prevents the CRDs list to update when a new CRD is created.
=> Fix API Manager bug in CRD add

__mocks__/namespaces.json, __mocks__/views.json, src/CRD/CRD.js, src/common/AppHeader.js, src/common/NamespaceSelect.js, src/home/Home.js, src/services/api/ApiInterface.js, src/services/api/ApiManager.js, src/services/api/__mocks__/ApiManager.js, test/AppHeader.test.js, test/AvailableList.test.js, test/AvailablePeer.test.js, test/ConnectedList.test.js, test/ConnectedPeer.test.js, test/ConnectionDetails.test.js, test/NamespaceSelect.test.js, test/PeerProperties.test.js, test/SideBar.test.js, test/Status.test.js
This PR adds a select in the header of the dashboard for namespaces, that let the user filter resources by namespaces.
Ref. #64
=> Add namespace select

src/resources/common/ResourceUtils.js, src/resources/resourceList/ResourceList.js, test/RTLUtils.js
This PR fixes a bug on namespace selection where selecting a namespace different from 'all namespaces' on resources that are not namespaced would trigger a 404.
=> Namespace select on not namespaced resources

src/editors/OAPIV3FormGenerator/CustomFieldTemplate.js, src/editors/OAPIV3FormGenerator/CustomFieldTemplateViewer.js, src/editors/OAPIV3FormGenerator/CustomWidget.js, test/UpdateCR.test.js
With this PR now the first collapsed object in a form view is always open. The others are (by default) collapsed.
=> Collapsed root form

__mocks__/dashboardconf.json, __mocks__/kubernetesjsonschema.json, __mocks__/pods.json, jest.setup.js, src/home/ConnectionDetails.js, src/resources/APIGroup/APIGroupList.js, src/resources/APIResourceList/APIResourceList.js, src/resources/common/DashboardConfigUtils.js, src/resources/common/KubernetesSchemaAutocomplete.js, src/resources/resourceList/ResourceList.js, src/resources/resourceList/ResourceListRenderer.js, src/resources/resourceList/columnContentFunction.js, src/services/TableUtils.js, src/services/api/ApiInterface.js, src/services/api/__mocks__/ApiManager.js, test/App.test.js, test/ColumnCustomization.test.js, test/FavouriteAndIcon.test.js, test/RTLUtils.js, test/ResourceList.test.js, test/SideBar.test.js
This PR adds the possibility to customize columns in the resources list view's table to add/remove resource's parameters displayed in the view:
- A column can be added clicking the ![image](https://user-images.githubusercontent.com/38859529/96736624-13640200-13bd-11eb-805d-0ed6eab2b579.png) *add column* button. A new column will spawn and a parameter (or more) can be selected in the search bar. Clicking the save button will save the new column in the dashboard config and from now on the new layout will be displayed for that specific resource.
- The search bar is provided with an autocomplete function that facilitate the user in the parameter selection.
- The title of the column can be updated simply clicking on the column title.
- A column can be deleted clicking on the column title and …
=> Column customization for resource lists

src/app/App.js, src/common/ResourceAutocomplete.js, src/editors/Editor.js, src/login/Login.js, src/resources/common/ResourceUtils.js, src/resources/resource/ResourceForm.js, src/resources/resource/ResourceHeader.js, src/resources/resourceList/ResourceList.js, src/services/api/ApiInterface.js, test/APIGroupList.test.js, test/AppHeader.test.js, test/CR.test.js, test/Login.test.js, test/NamespaceSelect.test.js, test/NewResource.test.js, test/ResourceList.test.js
This PR adds a button on the single resource view to edit a CRD using the form generated from its schema instead of just the JSON update tab.
ref. #67
=> Edit button with form on CRDs

src/resources/common/CustomIcon.js, src/resources/common/buttons/FavouriteButton.css, src/resources/common/buttons/FavouriteButton.js
This PR changes the default color of the favourite star that was the same as the background color, making it invisible.
ref. #67
=> Fix favourite star color

src/app/App.css, src/common/AppFooter.css, src/resources/resource/ResourceGeneral.js, src/resources/resource/ResourceHeader.js, src/styles/variables.less
This PR fixes some layout problems (footer floating and not sticking to the bottom, text overlay in some views)
=> General layout fixes

.github/workflows/node.js.yml
This PR upgrades the version of the Slack action used in CI pipeline.
=> Upgrade Slack action version

src/resources/resourceList/ResourceList.js
In this PR:
- Fixed bug where the dashboard would crash (or not work as intended) when adding a column in a list of resources with the same name as another column (for example, when trying to display two parameters called `name` but with different paths)
- If a column is called the same as another, the name will be changed automatically by applying a unique number after it
- The deletion of a column is now more user-friendly, giving the possibility to do such action through a delete button, after clicking on the column name (anyway, it is still possible to delete a column by leaving the column name input empty)
=> Fix duplicate column name bug and improved UX

src/common/SideBar.css, src/common/SideBar.js
This PR fixes a behavior of the sidebar where it would not stick to the top when scrolling down.
=> Fix sidebar not sticking to the top

src/resources/common/ResourceUtils.js, src/resources/resourceList/ResourceList.js
This PR fixes a bug where resources with the same name (but different namespace) would not be displayed in the list of resources (in fact, only one of them would be displayed, and not the others)
=> Fix resources with same name not showing in list
